#steps:
# # Build the container image
# - name: 'gcr.io/cloud-builders/docker'
#   args: [ 'build', '-t', 'us-central1-docker.pkg.dev/${_PROJECT_ID}/forecastweather14/forecastweather14:$COMMIT_SHA', '.' ]
# # Push the container image to Artifact Registry
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'us-central1-docker.pkg.dev/${_PROJECT_ID}/forecastweather14/forecastweather14:$COMMIT_SHA']
# # Deploy container image to Cloud Run
# - name: 'gcr.io/cloud-builders/gcloud'
#   entrypoint: gcloud
#   args:
#   - 'run'
#   - 'deploy'
#   - 'forecastweather14'
#   - '--image'
#   - 'us-central1-docker.pkg.dev/${_PROJECT_ID}/forecastweather14/forecastweather14:$COMMIT_SHA'
#   - '--region'
#   - 'us-central1'
#   - '--allow-unauthenticated'
#   - '--platform'
#   - 'managed'
#   - '--port'
#   - '8100'
#images:
# - 'us-central1-docker.pkg.dev/${_PROJECT_ID}/forecastweather14/forecastweather14'
#
#substitutions:
#  _PROJECT_ID: 'forecastweather14'


steps:
  # Grant permissions to push to Artifact Registry
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: gcloud
    args: ['projects', 'add-iam-policy-binding', '$forecastweather14', '--member=serviceAccount:$592434562240@cloudbuild.gserviceaccount.com', '--role=roles/artifactregistry.writer']
    dir: '/workspace'

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/${_PROJECT_ID}/forecastweather14/forecastweather14:$COMMIT_SHA', '.' ]

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/${_PROJECT_ID}/forecastweather14/forecastweather14:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'forecastweather14'
      - '--image'
      - 'us-central1-docker.pkg.dev/${_PROJECT_ID}/forecastweather14/forecastweather14:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--platform'
      - 'managed'
      - '--port'
      - '8100'

images:
  - 'us-central1-docker.pkg.dev/${_PROJECT_ID}/forecastweather14/forecastweather14'

substitutions:
  _PROJECT_ID: 'forecastweather14'
